"use client";

import type React from "react";
import { createContext, useContext, useState } from "react";

export type Language = "en" | "ro";

// Toate cheile de traducere – extinde după nevoie
const translationKeysEn = {
  "search.placeholder": "Search products...",
  "nav.admin": "Admin",
  "nav.cart": "Cart",
  "nav.orders": "Orders",
  "nav.signin": "Sign In",
  "nav.language": "Language",
  "nav.moderator": "Moderator",
  "nav.smartProjects": "Smart Projects",
  "nav.smartTechnologies": "Smart Technologies",
  "nav.smartComercial": "Smart Comercial",
  "nav.smartResidence": "Smart Residence",
  "nav.smartLighting": "Smart Lighting",
  "nav.smartIntercom": "Smart Intercom",
  "nav.products": "Products",
  "nav.about": "About",
  "nav.menu": "Menu",
  // Hero
  "hero.title": "Turn Your Home into a Smart Space",
  "hero.subtitle":
    "Discover the smart home world and enjoy the comfort and efficiency of modern technology. Your home control at a click away.",
  "hero.cta": "Explore Solutions",
  "hero.hotpoint.residence.label": "Smart residence",
  "hero.hotpoint.residence.desc": "Manage your home lighting from anywhere",
  "hero.hotpoint.comercial.label": "Smart Comercial",
  "hero.hotpoint.comercial.desc": "Manage your home lighting from anywhere",
  "hero.hotpoint.lighting.label": "Smart Lighting",
  "hero.hotpoint.lighting.desc": "Manage your home lighting from anywhere",
  "hero.hotpoint.intercom.label": "Smart Intercom",
  "hero.hotpoint.intercom.desc": "Keep the perfect temperature in every room",
  "hero.hotpoint.products.label": "Products",
  "hero.hotpoint.products.desc": "Control your home with voice only",
  "hero.hotpoint.about.label": "About",
  "hero.hotpoint.about.desc": "Create custom scenarios for your home",
  // Home sections
  "home.featuredTitle": "Recommended Products",
  "home.bundlesTitle": "Smart Home Bundles",
  "home.residentialTitle": "Residential Projects",
  "home.residentialSubtitle":
    "See how we turned ordinary homes into smart, efficient living spaces",
  "home.commercialTitle": "Commercial Projects",
  "home.commercialSubtitle":
    "See how we implemented smart solutions in commercial spaces for maximum efficiency",
  // Installations – residential
  "home.inst.res0.title": "Apartment",
  "home.inst.res0.desc":
    "Full automation for a modern apartment, with a focus on comfort and efficiency.",
  "home.inst.res0.f1": "Underfloor heating control",
  "home.inst.res0.f2": "Light control (on/off, dimming, sensors for auto-on)",
  "home.inst.res0.f3": "AC control",
  "home.inst.res0.f4": "4-zone audio",
  "home.inst.res0.f5": "Blind control",
  "home.inst.res0.f6": "Curtain control",
  "home.inst.res0.f7": "Control and view on phone",
  "home.inst.res0.f8": "Intercom",
  "home.inst.res0.f9": "Scenarios",
  "home.inst.res1.title": "Wooden holiday home",
  "home.inst.res1.desc":
    "Smart solution for a holiday home, designed for security and remote control.",
  "home.inst.res1.f1": "Heating control",
  "home.inst.res1.f2": "Light control (on/off, dimming, sensors for auto-on)",
  "home.inst.res1.f3": "Blind control",
  "home.inst.res1.f4": "Scenarios",
  "home.inst.res1.f5": "Intercom and access control",
  "home.inst.res1.f6": "Control and view on phone",
  "home.inst.res2.title": "Villa",
  "home.inst.res2.desc":
    "Advanced automation for a villa, with full integration of all technical systems.",
  "home.inst.res2.f1": "Underfloor heating control",
  "home.inst.res2.f2": "Light control (on/off, dimming, sensors for auto-on)",
  "home.inst.res2.f3": "Fan coil control",
  "home.inst.res2.f4": "6-zone audio",
  "home.inst.res2.f5": "Blind control",
  "home.inst.res2.f6": "Heat pump and solar panel integration",
  "home.inst.res2.f7": "Integrated alarm system",
  "home.inst.res2.f8": "CCTV camera view",
  "home.inst.res2.f9": "Weather station",
  "home.inst.res2.f10": "Intercom and access control",
  "home.inst.res2.f11": "Control and view on phone",
  // Installations – commercial
  "home.inst.comm0.title": "Floreasca Office Building",
  "home.inst.comm0.desc":
    "Complex automation system for a 6-floor office building, including access control and energy management.",
  "home.inst.comm0.s1": "Energy Savings",
  "home.inst.comm0.s2": "Area",
  "home.inst.comm0.s3": "Devices",
  "home.inst.comm0.s4": "ROI",
  "home.inst.comm0.s4value": "2 years",
  "home.inst.comm1.title": "Boutique Hotel Centru",
  "home.inst.comm1.desc":
    "Complete hotel automation solution with individual control for 28 rooms.",
  "home.inst.comm1.s1": "Energy Savings",
  "home.inst.comm1.s2": "Rooms",
  "home.inst.comm1.s3": "Devices",
  "home.inst.comm1.s4": "Satisfaction",
  "home.inst.comm2.title": "Restaurant Smart Decebal",
  "home.inst.comm2.desc":
    "Integrated control system for lighting, HVAC and ambience, focused on customer experience.",
  "home.inst.comm2.s1": "Energy Savings",
  "home.inst.comm2.s2": "Control Zones",
  "home.inst.comm2.s3": "Devices",
  "home.inst.comm2.s4": "ROI",
  "home.inst.comm2.s4value": "18 months",
  "newsletter.lead": "Stay up to date with SmartHomeMall",
  "newsletter.title": "Subscribe to our Newsletter!",
  "newsletter.description":
    "Stay up to date with the latest SmartHomeMall promotions and products! We won't bother you too often, we'll only write when we have something that fits you!",
  "newsletter.placeholder": "Email",
  "newsletter.button": "SUBSCRIBE",
  "newsletter.buttonLoading": "PROCESSING...",
  "newsletter.success": "Success!",
  "newsletter.successDesc": "You have successfully subscribed to the newsletter!",
  "newsletter.error": "Error",
  "newsletter.errorDesc": "An error occurred while subscribing. Please try again.",
  // Bundle showcase
  "bundle.sale": "Sale",
  "bundle.badge": "Bundle",
  "bundle.includes": "Includes:",
  "bundle.addToCart": "Add to cart (coming soon)",
  "bundle.viewDetails": "View details",
  "bundle.addToCartTitle": "Online store not yet active",
  // Footer
  "footer.tagline":
    "Smart solutions for modern homes and businesses. Automation, security and comfort at a click away.",
  "footer.pages": "Pages",
  "footer.info": "Information",
  "footer.termsAndConditions": "Terms and Conditions",
  "footer.privacyPolicy": "Privacy Policy",
  "footer.contact": "Contact",
  "footer.allRightsReserved": "All rights reserved.",
  "footer.termsShort": "Terms",
  "footer.privacyShort": "Privacy",
  "footer.address": "Sample St. 123, Bucharest",
  // Smart Residence
  "residence.hero.title": "Smart Residence",
  "residence.hero.subtitle": "Turn your home into a smart, secure and energy-efficient space.",
  "residence.hero.badge1": "Total Control",
  "residence.hero.badge2": "Advanced Security",
  "residence.hero.badge3": "Smart Lighting",
  "residence.hero.badge4": "Smart Climate",
  "residence.hotspot.hub.label": "Hub",
  "residence.hotspot.hub.desc": "The control center of your smart home. Connect and manage all smart devices.",
  "residence.hotspot.lights.label": "Smart Lights",
  "residence.hotspot.lights.desc": "Control your home lighting remotely or automated.",
  "residence.hotspot.intercom.label": "Smart Intercom",
  "residence.hotspot.intercom.desc": "Easily communicate with visitors and control access to your home.",
  "residence.hotspot.thermostat.label": "Smart Thermostat",
  "residence.hotspot.thermostat.desc": "Adjust temperature for comfort and energy efficiency.",
  "residence.hotspot.blinds.label": "Blinds",
  "residence.hotspot.blinds.desc": "Automated blinds for light and privacy control.",
  "residence.hotspot.ac.label": "AC",
  "residence.hotspot.ac.desc": "Smart air conditioning for a perfect climate.",
  "residence.explore.title": "Explore the Smart Home",
  "residence.explore.hint": "Touch or hover over points for details.",
  "residence.life.title": "How does a smart home improve your life?",
  "residence.life.c1.title": "Personalized Comfort",
  "residence.life.c1.desc": "Control lights, temperature and devices from anywhere in the house, right from your phone.",
  "residence.life.c2.title": "Advanced Security",
  "residence.life.c2.desc": "Monitor and secure your home with sensors, cameras and smart alerts, wherever you are.",
  "residence.life.c3.title": "Energy Efficiency",
  "residence.life.c3.desc": "Optimize energy use and reduce costs with smart solutions for every room.",
  "residence.what.title": "What is a smart home?",
  "residence.what.p": "A smart home integrates technology to give you control, security and enhanced comfort. Smart devices communicate with each other and can be managed remotely, adapting to your daily needs.",
  "residence.what.li1": "Automation for lighting, climate and security",
  "residence.what.li2": "Voice and remote control",
  "residence.what.li3": "Real-time monitoring",
  "residence.help.title": "How can we help with smart residence projects?",
  "residence.help.c1.title": "Single homes & villas",
  "residence.help.c1.li1": "Full control for lighting, climate, blinds and security",
  "residence.help.c1.li2": "Smart access with fingerprint, code or phone",
  "residence.help.c1.li3": "Video monitoring and instant alerts",
  "residence.help.c2.title": "Apartment buildings",
  "residence.help.c2.li1": "Video intercom and controlled access for residents",
  "residence.help.c2.li2": "Elevators that are called automatically when you approach the building",
  "residence.help.c2.li3": "Lighting and climate for common areas, automated",
  "residence.help.c3.title": "Residential areas & gated communities",
  "residence.help.c3.li1": "Automatic barrier with license plate recognition",
  "residence.help.c3.li2": "Centralized management for all homes",
  "residence.help.c3.li3": "Visitor and delivery access with temporary code",
  "residence.help.closing": "Regardless of project type, we offer tailored solutions for comfort, security and energy efficiency. From smart home control to automation for entire residential complexes, we are your trusted partner for a smart future.",
  "residence.products.title": "Smart Products for Your Home",
  // Smart Comercial
  "comercial.hero.title": "Smart Comercial",
  "comercial.hero.subtitle": "Transform your business with smart solutions. Increase efficiency, security and customer experience with state-of-the-art technology.",
  "comercial.hero.cta": "Learn more",
  "comercial.solutions.title": "Smart Solutions for Any Business",
  "comercial.solutions.retail.title": "Retail & Stores",
  "comercial.solutions.retail.f1": "Smart inventory tracking",
  "comercial.solutions.retail.f2": "Automated payment systems",
  "comercial.solutions.retail.f3": "Customer behavior analysis",
  "comercial.solutions.retail.f4": "Energy management",
  "comercial.solutions.retail.f5": "Security systems",
  "comercial.solutions.hotel.title": "Hotels & Hospitality",
  "comercial.solutions.hotel.f1": "Automated check-in/out",
  "comercial.solutions.hotel.f2": "Room automation",
  "comercial.solutions.hotel.f3": "Energy optimization",
  "comercial.solutions.hotel.f4": "Enhanced guest experience",
  "comercial.solutions.hotel.f5": "Staff management",
  "comercial.solutions.office.title": "Offices & Workspaces",
  "comercial.solutions.office.f1": "Access control",
  "comercial.solutions.office.f2": "Meeting room management",
  "comercial.solutions.office.f3": "Climate control",
  "comercial.solutions.office.f4": "Occupancy monitoring",
  "comercial.solutions.office.f5": "Energy efficiency",
  "comercial.process.title": "Our Implementation Process",
  "comercial.process.s1.title": "Analysis & Planning",
  "comercial.process.s1.desc": "We start with a full assessment of your business needs, analyzing current systems and identifying opportunities for smart automation.",
  "comercial.process.s1.d1": "Site assessment",
  "comercial.process.s1.d2": "Requirements gathering",
  "comercial.process.s1.d3": "System architecture planning",
  "comercial.process.s1.d4": "ROI analysis",
  "comercial.process.s2.title": "Custom Design",
  "comercial.process.s2.desc": "Our team designs a smart solution tailored to your business requirements and goals.",
  "comercial.process.s2.d1": "Technical specifications",
  "comercial.process.s2.d2": "Integration planning",
  "comercial.process.s2.d3": "User interface design",
  "comercial.process.s2.d4": "Security protocols",
  "comercial.process.s3.title": "Professional Installation",
  "comercial.process.s3.desc": "Expert installation of all smart systems, with minimal disruption to your operations.",
  "comercial.process.s3.d1": "Hardware installation",
  "comercial.process.s3.d2": "Software implementation",
  "comercial.process.s3.d3": "System integration",
  "comercial.process.s3.d4": "Quality testing",
  "comercial.process.s4.title": "Training & Support",
  "comercial.process.s4.desc": "Comprehensive training for your team and ongoing support for optimal smart system performance.",
  "comercial.process.s4.d1": "Staff training",
  "comercial.process.s4.d2": "Documentation",
  "comercial.process.s4.d3": "24/7 support",
  "comercial.process.s4.d4": "Regular maintenance",
  "comercial.benefits.title": "Key Benefits",
  "comercial.benefits.b1": "Increased Operational Efficiency",
  "comercial.benefits.b2": "Lower Operating Costs",
  "comercial.benefits.b3": "Enhanced Security",
  "comercial.benefits.b4": "Centralized Management",
  "comercial.products.title": "Smart Products for Your Business",
  // Smart Lighting
  "lighting.hero.title": "Smart Lighting",
  "lighting.hero.subtitle": "Smart lighting for any mood, with energy savings and full control. Create the perfect atmosphere, anytime.",
  "lighting.hero.badge1": "Total Control",
  "lighting.hero.badge2": "Custom Scenes",
  "lighting.hero.badge3": "Energy Efficiency",
  "lighting.hero.badge4": "Remote Control",
  "lighting.moods.relax": "Relax",
  "lighting.moods.focus": "Focus",
  "lighting.moods.party": "Party",
  "lighting.moods.night": "Night",
  "lighting.energy.title": "How do you save energy with smart lighting?",
  "lighting.energy.e1": "Presence sensors: Lights turn on only when you need them.",
  "lighting.energy.e2": "Automatic brightness adjustment based on natural light.",
  "lighting.energy.e3": "Custom scenarios for every moment of the day.",
  "lighting.energy.e4": "Remote control and automatic scheduling.",
  "lighting.energy.e5": "Reduce consumption by up to 60% compared to traditional lighting.",
  "lighting.process.title": "How does smart lighting work?",
  "lighting.process.s1.title": "Automatic detection",
  "lighting.process.s1.desc": "Sensors detect presence and natural light level",
  "lighting.process.s2.title": "Smart processing",
  "lighting.process.s2.desc": "The system analyzes data and determines optimal settings",
  "lighting.process.s3.title": "Dynamic adjustment",
  "lighting.process.s3.desc": "Lights adapt automatically to ambient conditions",
  "lighting.process.s4.title": "Total control",
  "lighting.process.s4.desc": "Control everything from the app or with voice commands",
  "lighting.process.b1": "Up to 60% consumption reduction",
  "lighting.process.b2": "Sustainable and eco-friendly",
  "lighting.process.b3": "Minimal maintenance",
  "lighting.process.b4": "Precise and personalized control",
  "lighting.moodvideo.title": "Control the light in your home",
  "lighting.moodvideo.start": "Start the day",
  "lighting.moodvideo.end": "End the day",
  "lighting.products.title": "Smart Products for Lighting",
  // Smart Intercom
  "intercom.hero.title": "Smart Intercom",
  "intercom.hero.subtitle": "Turn your entrance into a smart and secure experience",
  "intercom.hero.badge1": "HD Video",
  "intercom.hero.badge2": "Secure Access",
  "intercom.hero.badge3": "App Control",
  "intercom.hero.badge4": "Instant Notifications",
  "intercom.setup.title": "Simple Setup in 4 Steps",
  "intercom.setup.s1.title": "Hardware Installation",
  "intercom.setup.s1.desc": "Mount the outdoor unit and connect it to the power supply",
  "intercom.setup.s1.d1": "Mount unit at the right height",
  "intercom.setup.s1.d2": "Connect to power supply",
  "intercom.setup.s1.d3": "Check camera angle",
  "intercom.setup.s1.d4": "Test doorbell operation",
  "intercom.setup.s2.title": "WiFi Connection",
  "intercom.setup.s2.desc": "Connect the intercom to your WiFi network for remote access",
  "intercom.setup.s2.d1": "Download the mobile app",
  "intercom.setup.s2.d2": "Scan the QR code on the device",
  "intercom.setup.s2.d3": "Select WiFi network",
  "intercom.setup.s2.d4": "Enter network password",
  "intercom.setup.s3.title": "App Configuration",
  "intercom.setup.s3.desc": "Customize settings and add additional users",
  "intercom.setup.s3.d1": "Create account in app",
  "intercom.setup.s3.d2": "Set notification preferences",
  "intercom.setup.s3.d3": "Add family members",
  "intercom.setup.s3.d4": "Configure access codes",
  "intercom.setup.s4.title": "Testing & Completion",
  "intercom.setup.s4.desc": "Verify all functions and complete setup",
  "intercom.setup.s4.d1": "Test audio-video communication",
  "intercom.setup.s4.d2": "Check push notifications",
  "intercom.setup.s4.d3": "Test door opening",
  "intercom.setup.s4.d4": "Configure automated scenarios",
  "intercom.features.title": "Advanced Features",
  "intercom.features.f1.title": "HD Video & Night Vision",
  "intercom.features.f1.desc": "HD camera with night vision and 160° wide angle",
  "intercom.features.f1.d1": "1080p resolution",
  "intercom.features.f1.d2": "IR night vision",
  "intercom.features.f1.d3": "Wide viewing angle",
  "intercom.features.f1.d4": "Motion sensor",
  "intercom.features.f2.title": "Bidirectional Audio",
  "intercom.features.f2.desc": "Clear two-way communication with noise reduction",
  "intercom.features.f2.d1": "HD microphone",
  "intercom.features.f2.d2": "Noise reduction",
  "intercom.features.f2.d3": "Echo cancellation",
  "intercom.features.f2.d4": "Adjustable volume",
  "intercom.features.f3.title": "Access Control",
  "intercom.features.f3.desc": "Multiple access methods and user management",
  "intercom.features.f3.d1": "PIN codes",
  "intercom.features.f3.d2": "RFID cards",
  "intercom.features.f3.d3": "Fingerprint",
  "intercom.features.f3.d4": "Facial recognition",
  "intercom.features.f4.title": "Smart Integration",
  "intercom.features.f4.desc": "Integration with smart home ecosystem and automation",
  "intercom.features.f4.d1": "App control",
  "intercom.features.f4.d2": "Alexa/Google integration",
  "intercom.features.f4.d3": "IFTTT automation",
  "intercom.features.f4.d4": "Open API",
  "intercom.usecases.title": "Use Cases",
  "intercom.usecases.family.title": "For Families",
  "intercom.usecases.family.s1": "Monitor children when they get home",
  "intercom.usecases.family.s2": "Access for nannies or caregivers",
  "intercom.usecases.family.s3": "Communicate with visitors when you're away",
  "intercom.usecases.family.s4": "Video recording for security",
  "intercom.usecases.business.title": "For Business",
  "intercom.usecases.business.s1": "Employee access control",
  "intercom.usecases.business.s2": "Visit scheduling",
  "intercom.usecases.business.s3": "Delivery monitoring",
  "intercom.usecases.business.s4": "Full access history",
  "intercom.usecases.vacation.title": "For Vacations",
  "intercom.usecases.vacation.s1": "Access for Airbnb guests",
  "intercom.usecases.vacation.s2": "Remote monitoring",
  "intercom.usecases.vacation.s3": "Temporary access codes",
  "intercom.usecases.vacation.s4": "Communication with cleaning services",
  "intercom.security.title": "Security and Privacy",
  "intercom.security.e2e.title": "End-to-End Encryption",
  "intercom.security.e2e.desc": "All video and audio communications are encrypted for maximum security",
  "intercom.security.control.title": "Full Data Control",
  "intercom.security.control.desc": "You decide how long recordings are kept and who has access to them",
  "intercom.security.protection.title": "Advanced Protection",
  "intercom.security.protection.desc": "Anti-tamper system and real-time alerts for suspicious activity",
  "intercom.products.title": "Smart Products for Your Intercom",
} as const;

const translationKeysRo: Record<keyof typeof translationKeysEn, string> = {
  "search.placeholder": "Caută produse...",
  "nav.admin": "Admin",
  "nav.cart": "Coș",
  "nav.orders": "Comenzi",
  "nav.signin": "Autentificare",
  "nav.language": "Limbă",
  "nav.moderator": "Moderator",
  "nav.smartProjects": "Smart Projects",
  "nav.smartTechnologies": "Smart Technologies",
  "nav.smartComercial": "Smart Comercial",
  "nav.smartResidence": "Smart Residence",
  "nav.smartLighting": "Smart Lighting",
  "nav.smartIntercom": "Smart Intercom",
  "nav.products": "Produse",
  "nav.about": "Despre",
  "nav.menu": "Meniu",
  "hero.title": "Transformă-ți Casa într-un Spațiu Inteligent",
  "hero.subtitle":
    "Descoperă lumea smart home și bucură-te de confortul și eficiența oferită de tehnologia modernă. Controlul casei tale la un click distanță.",
  "hero.cta": "Explorează Soluțiile",
  "hero.hotpoint.residence.label": "Smart residence",
  "hero.hotpoint.residence.desc": "Gestionează iluminatul casei tale din orice locație",
  "hero.hotpoint.comercial.label": "Smart Comercial",
  "hero.hotpoint.comercial.desc": "Gestionează iluminatul casei tale din orice locație",
  "hero.hotpoint.lighting.label": "Smart Lighting",
  "hero.hotpoint.lighting.desc": "Gestionează iluminatul casei tale din orice locație",
  "hero.hotpoint.intercom.label": "Smart Intercom",
  "hero.hotpoint.intercom.desc": "Menține temperatura perfectă în fiecare cameră",
  "hero.hotpoint.products.label": "Produse",
  "hero.hotpoint.products.desc": "Comandă-ți casa folosind doar vocea",
  "hero.hotpoint.about.label": "Despre",
  "hero.hotpoint.about.desc": "Creează scenarii personalizate pentru casa ta",
  "home.featuredTitle": "Produse Recomandate",
  "home.bundlesTitle": "Pachete Smart Home",
  "home.residentialTitle": "Proiecte Rezidențiale",
  "home.residentialSubtitle":
    "Descoperă cum am transformat case obișnuite în locuințe inteligente și eficiente",
  "home.commercialTitle": "Proiecte Comerciale",
  "home.commercialSubtitle":
    "Vezi cum am implementat soluții smart în spații comerciale pentru eficiență maximă",
  "home.inst.res0.title": "Apartament",
  "home.inst.res0.desc":
    "Automatizare completă pentru un apartament modern, cu accent pe confort și eficiență.",
  "home.inst.res0.f1": "Control încălzire în pardoseală",
  "home.inst.res0.f2": "Control lumini (on/off, dimming, senzori pentru aprindere automată)",
  "home.inst.res0.f3": "Control AC",
  "home.inst.res0.f4": "Redare audio 4 zone",
  "home.inst.res0.f5": "Control rulouri",
  "home.inst.res0.f6": "Control draperii",
  "home.inst.res0.f7": "Control și vizualizare pe telefon",
  "home.inst.res0.f8": "Interfon",
  "home.inst.res0.f9": "Scenarii",
  "home.inst.res1.title": "Casă de vacanță din lemn",
  "home.inst.res1.desc":
    "Soluție smart pentru o casă de vacanță, gândită pentru siguranță și control de la distanță.",
  "home.inst.res1.f1": "Control încălzire",
  "home.inst.res1.f2": "Control lumini (on/off, dimming, senzori pentru aprindere automată)",
  "home.inst.res1.f3": "Control rulouri",
  "home.inst.res1.f4": "Scenarii",
  "home.inst.res1.f5": "Interfon și control acces",
  "home.inst.res1.f6": "Control și vizualizare pe telefon",
  "home.inst.res2.title": "Vilă",
  "home.inst.res2.desc":
    "Automatizare avansată pentru vilă, cu integrare completă a tuturor sistemelor tehnice.",
  "home.inst.res2.f1": "Control încălzire în pardoseală",
  "home.inst.res2.f2": "Control lumini (on/off, dimming, senzori pentru aprindere automată)",
  "home.inst.res2.f3": "Control ventiloconvectoare",
  "home.inst.res2.f4": "Redare audio 6 zone",
  "home.inst.res2.f5": "Control rulouri",
  "home.inst.res2.f6": "Integrare cu pompă de căldură și panouri solare",
  "home.inst.res2.f7": "Sistem de alarmă integrat",
  "home.inst.res2.f8": "Vizualizare camere CCTV",
  "home.inst.res2.f9": "Stație meteo",
  "home.inst.res2.f10": "Interfon și control acces",
  "home.inst.res2.f11": "Control și vizualizare pe telefon",
  "home.inst.comm0.title": "Clădire de Birouri Floreasca",
  "home.inst.comm0.desc":
    "Sistem complex de automatizare pentru o clădire de birouri cu 6 etaje, incluzând control acces și management energetic.",
  "home.inst.comm0.s1": "Economie Energie",
  "home.inst.comm0.s2": "Suprafață",
  "home.inst.comm0.s3": "Dispozitive",
  "home.inst.comm0.s4": "ROI",
  "home.inst.comm0.s4value": "2 ani",
  "home.inst.comm1.title": "Hotel Boutique Centru",
  "home.inst.comm1.desc":
    "Soluție completă de automatizare hotelieră cu control individual pentru 28 de camere.",
  "home.inst.comm1.s1": "Economie Energie",
  "home.inst.comm1.s2": "Camere",
  "home.inst.comm1.s3": "Dispozitive",
  "home.inst.comm1.s4": "Satisfacție",
  "home.inst.comm2.title": "Restaurant Smart Decebal",
  "home.inst.comm2.desc":
    "Sistem integrat de control pentru iluminat, HVAC și ambianță, cu focus pe experiența clientului.",
  "home.inst.comm2.s1": "Economie Energie",
  "home.inst.comm2.s2": "Zone Control",
  "home.inst.comm2.s3": "Dispozitive",
  "home.inst.comm2.s4": "ROI",
  "home.inst.comm2.s4value": "18 luni",
  "newsletter.lead": "Fii la curent cu SmartHomeMall",
  "newsletter.title": "Abonează-te la Newsletter!",
  "newsletter.description":
    "Fii mereu la curent cu ultimele promoții și produse SmartHomeMall! Nu te vom deranja prea des, îți vom scrie doar când e ceva care ți se potrivește!",
  "newsletter.placeholder": "Email",
  "newsletter.button": "ABONEAZĂ-TE",
  "newsletter.buttonLoading": "SE PROCESEAZĂ...",
  "newsletter.success": "Succes!",
  "newsletter.successDesc": "Te-ai abonat cu succes la newsletter!",
  "newsletter.error": "Eroare",
  "newsletter.errorDesc": "A apărut o eroare la abonare. Te rugăm să încerci din nou.",
  "bundle.sale": "Sale",
  "bundle.badge": "Bundle",
  "bundle.includes": "Include:",
  "bundle.addToCart": "Adaugă în coș (în curând)",
  "bundle.viewDetails": "Arată detalii",
  "bundle.addToCartTitle": "Magazinul online nu este încă activ",
  "footer.tagline":
    "Soluții inteligente pentru locuințe și afaceri moderne. Automatizare, securitate și confort la un click distanță.",
  "footer.pages": "Pagini",
  "footer.info": "Informații",
  "footer.termsAndConditions": "Termeni și Condiții",
  "footer.privacyPolicy": "Politica de Confidențialitate",
  "footer.contact": "Contact",
  "footer.allRightsReserved": "Toate drepturile rezervate.",
  "footer.termsShort": "Termeni",
  "footer.privacyShort": "Confidențialitate",
  "footer.address": "Str. Exemplu 123, București",
  "residence.hero.title": "Smart Residence",
  "residence.hero.subtitle": "Transformă-ți locuința într-un spațiu inteligent, sigur și eficient energetic.",
  "residence.hero.badge1": "Control Total",
  "residence.hero.badge2": "Securitate Avansată",
  "residence.hero.badge3": "Iluminat Smart",
  "residence.hero.badge4": "Climat Inteligent",
  "residence.hotspot.hub.label": "Hub",
  "residence.hotspot.hub.desc": "Centrul de control al casei inteligente. Conectează și gestionează toate dispozitivele smart.",
  "residence.hotspot.lights.label": "Smart Lights",
  "residence.hotspot.lights.desc": "Controlează iluminatul casei de la distanță sau automatizat.",
  "residence.hotspot.intercom.label": "Smart Intercom",
  "residence.hotspot.intercom.desc": "Comunică ușor cu vizitatorii și controlează accesul în locuință.",
  "residence.hotspot.thermostat.label": "Smart Thermostat",
  "residence.hotspot.thermostat.desc": "Reglează temperatura pentru confort și eficiență energetică.",
  "residence.hotspot.blinds.label": "Blinds",
  "residence.hotspot.blinds.desc": "Jaluzele automate pentru controlul luminii și intimității.",
  "residence.hotspot.ac.label": "AC",
  "residence.hotspot.ac.desc": "Aer condiționat inteligent pentru un climat perfect.",
  "residence.explore.title": "Explorează Casa Inteligentă",
  "residence.explore.hint": "Atinge sau plasează cursorul pe puncte pentru detalii.",
  "residence.life.title": "Cum îți îmbunătățește viața o casă smart?",
  "residence.life.c1.title": "Confort Personalizat",
  "residence.life.c1.desc": "Controlezi luminile, temperatura și dispozitivele din orice colț al casei, direct de pe telefon.",
  "residence.life.c2.title": "Siguranță Avansată",
  "residence.life.c2.desc": "Monitorizezi și securizezi locuința cu senzori, camere și alerte inteligente, oriunde te-ai afla.",
  "residence.life.c3.title": "Eficiență Energetică",
  "residence.life.c3.desc": "Optimizezi consumul de energie și reduci costurile cu soluții smart pentru fiecare cameră.",
  "residence.what.title": "Ce este o casă inteligentă?",
  "residence.what.p": "O casă inteligentă integrează tehnologia pentru a-ți oferi control, siguranță și confort sporit. Dispozitivele smart comunică între ele și pot fi gestionate de la distanță, adaptându-se nevoilor tale zilnice.",
  "residence.what.li1": "Automatizare pentru lumină, climat și securitate",
  "residence.what.li2": "Control vocal și de la distanță",
  "residence.what.li3": "Monitorizare în timp real",
  "residence.help.title": "Cum te putem ajuta cu proiectele de smart residence?",
  "residence.help.c1.title": "Case individuale & vile",
  "residence.help.c1.li1": "Control total pentru lumină, climat, jaluzele și securitate",
  "residence.help.c1.li2": "Acces smart cu amprentă, cod sau telefon",
  "residence.help.c1.li3": "Monitorizare video și alerte instant",
  "residence.help.c2.title": "Blocuri de apartamente",
  "residence.help.c2.li1": "Interfonie video și acces controlat pentru locatari",
  "residence.help.c2.li2": "Lifturi care se cheamă automat când te apropii de clădire",
  "residence.help.c2.li3": "Iluminat și climatizare pe zone comune, automatizate",
  "residence.help.c3.title": "Cartiere rezidențiale & gated communities",
  "residence.help.c3.li1": "Barieră automată cu recunoaștere a plăcuței de înmatriculare",
  "residence.help.c3.li2": "Management centralizat pentru toate locuințele",
  "residence.help.c3.li3": "Acces vizitatori și livrări cu cod temporar",
  "residence.help.closing": "Indiferent de tipul proiectului, oferim soluții personalizate pentru confort, siguranță și eficiență energetică. De la controlul inteligent al locuinței până la automatizări pentru întregul ansamblu rezidențial, suntem partenerul tău de încredere pentru un viitor smart.",
  "residence.products.title": "Produse Smart pentru Casa Ta",
  "comercial.hero.title": "Smart Comercial",
  "comercial.hero.subtitle": "Transformă-ți afacerea cu soluții inteligente. Crește eficiența, securitatea și experiența clienților cu tehnologie de ultimă generație.",
  "comercial.hero.cta": "Află mai multe",
  "comercial.solutions.title": "Soluții Smart pentru Orice Afacere",
  "comercial.solutions.retail.title": "Retail & Magazine",
  "comercial.solutions.retail.f1": "Urmărirea inteligentă a stocurilor",
  "comercial.solutions.retail.f2": "Sisteme automate de plată",
  "comercial.solutions.retail.f3": "Analiza comportamentului clienților",
  "comercial.solutions.retail.f4": "Management energetic",
  "comercial.solutions.retail.f5": "Sisteme de securitate",
  "comercial.solutions.hotel.title": "Hoteluri & Ospitalitate",
  "comercial.solutions.hotel.f1": "Check-in/out automatizat",
  "comercial.solutions.hotel.f2": "Automatizarea camerelor",
  "comercial.solutions.hotel.f3": "Optimizare energetică",
  "comercial.solutions.hotel.f4": "Îmbunătățirea experienței oaspeților",
  "comercial.solutions.hotel.f5": "Managementul personalului",
  "comercial.solutions.office.title": "Birouri & Spații de Lucru",
  "comercial.solutions.office.f1": "Control acces",
  "comercial.solutions.office.f2": "Managementul sălilor de ședințe",
  "comercial.solutions.office.f3": "Control climatizare",
  "comercial.solutions.office.f4": "Monitorizare ocupare",
  "comercial.solutions.office.f5": "Eficiență energetică",
  "comercial.process.title": "Procesul Nostru de Implementare",
  "comercial.process.s1.title": "Analiză & Planificare",
  "comercial.process.s1.desc": "Începem cu o evaluare completă a nevoilor afacerii tale, analizând sistemele actuale și identificând oportunități pentru automatizare inteligentă.",
  "comercial.process.s1.d1": "Evaluarea locației",
  "comercial.process.s1.d2": "Colectarea cerințelor",
  "comercial.process.s1.d3": "Planificarea arhitecturii sistemului",
  "comercial.process.s1.d4": "Analiza ROI",
  "comercial.process.s2.title": "Design Personalizat",
  "comercial.process.s2.desc": "Echipa noastră proiectează o soluție smart adaptată perfect cerințelor și obiectivelor afacerii tale.",
  "comercial.process.s2.d1": "Specificații tehnice",
  "comercial.process.s2.d2": "Planificarea integrării",
  "comercial.process.s2.d3": "Design interfață utilizator",
  "comercial.process.s2.d4": "Protocoale de securitate",
  "comercial.process.s3.title": "Instalare Profesională",
  "comercial.process.s3.desc": "Instalare expertă a tuturor sistemelor smart, asigurând perturbări minime ale operațiunilor afacerii tale.",
  "comercial.process.s3.d1": "Instalare hardware",
  "comercial.process.s3.d2": "Implementare software",
  "comercial.process.s3.d3": "Integrare sisteme",
  "comercial.process.s3.d4": "Testare calitate",
  "comercial.process.s4.title": "Training & Suport",
  "comercial.process.s4.desc": "Training comprehensiv pentru echipa ta și suport continuu pentru a asigura funcționarea optimă a sistemelor smart.",
  "comercial.process.s4.d1": "Instruirea personalului",
  "comercial.process.s4.d2": "Documentație",
  "comercial.process.s4.d3": "Suport 24/7",
  "comercial.process.s4.d4": "Mentenanță regulată",
  "comercial.benefits.title": "Beneficii Cheie",
  "comercial.benefits.b1": "Eficiență Operațională Crescută",
  "comercial.benefits.b2": "Reducerea Costurilor de Operare",
  "comercial.benefits.b3": "Securitate Îmbunătățită",
  "comercial.benefits.b4": "Management Centralizat",
  "comercial.products.title": "Produse Smart pentru Afacerea Ta",
  "lighting.hero.title": "Smart Lighting",
  "lighting.hero.subtitle": "Iluminat inteligent pentru orice stare, cu economie de energie și control total. Creează atmosfera perfectă, oricând.",
  "lighting.hero.badge1": "Control Total",
  "lighting.hero.badge2": "Scene Personalizate",
  "lighting.hero.badge3": "Eficiență Energetică",
  "lighting.hero.badge4": "Control de la Distanță",
  "lighting.moods.relax": "Relax",
  "lighting.moods.focus": "Focus",
  "lighting.moods.party": "Party",
  "lighting.moods.night": "Night",
  "lighting.energy.title": "Cum economisești energie cu iluminatul smart?",
  "lighting.energy.e1": "Senzori de prezență: Luminile se aprind doar când ai nevoie.",
  "lighting.energy.e2": "Reglare automată a intensității în funcție de lumina naturală.",
  "lighting.energy.e3": "Scenarii personalizate pentru fiecare moment al zilei.",
  "lighting.energy.e4": "Control de la distanță și programare automată.",
  "lighting.energy.e5": "Reduci consumul cu până la 60% față de iluminatul clasic.",
  "lighting.process.title": "Cum funcționează iluminatul inteligent?",
  "lighting.process.s1.title": "Detectare automată",
  "lighting.process.s1.desc": "Senzorii detectează prezența și nivelul de lumină naturală",
  "lighting.process.s2.title": "Procesare inteligentă",
  "lighting.process.s2.desc": "Sistemul analizează datele și determină setările optime",
  "lighting.process.s3.title": "Ajustare dinamică",
  "lighting.process.s3.desc": "Luminile se adaptează automat la condițiile ambientale",
  "lighting.process.s4.title": "Control total",
  "lighting.process.s4.desc": "Controlează totul din aplicație sau prin comenzi vocale",
  "lighting.process.b1": "Reducere consum până la 60%",
  "lighting.process.b2": "Sustenabil și eco-friendly",
  "lighting.process.b3": "Întreținere minimă",
  "lighting.process.b4": "Control precis și personalizat",
  "lighting.moodvideo.title": "Controlează lumina casei tale",
  "lighting.moodvideo.start": "Incepe ziua",
  "lighting.moodvideo.end": "Termina ziua",
  "lighting.products.title": "Produse Smart pentru Iluminat",
  "intercom.setup.title": "Configurare Simplă în 4 Pași",
  "intercom.hero.title": "Smart Intercom",
  "intercom.hero.subtitle": "Transformă intrarea în casa ta într-o experiență inteligentă și sigură",
  "intercom.hero.badge1": "Video HD",
  "intercom.hero.badge2": "Acces Securizat",
  "intercom.hero.badge3": "Control din Aplicație",
  "intercom.hero.badge4": "Notificări Instant",
  "intercom.setup.s1.title": "Instalare Hardware",
  "intercom.setup.s1.desc": "Montează unitatea exterioară și conecteaz-o la sursa de alimentare",
  "intercom.setup.s1.d1": "Fixează unitatea la înălțimea potrivită",
  "intercom.setup.s1.d2": "Conectează la sursa de alimentare",
  "intercom.setup.s1.d3": "Verifică unghiul camerei video",
  "intercom.setup.s1.d4": "Testează funcționarea soneriei",
  "intercom.setup.s2.title": "Conectare WiFi",
  "intercom.setup.s2.desc": "Conectează intercom-ul la rețeaua WiFi pentru acces de la distanță",
  "intercom.setup.s2.d1": "Descarcă aplicația mobilă",
  "intercom.setup.s2.d2": "Scanează codul QR de pe dispozitiv",
  "intercom.setup.s2.d3": "Selectează rețeaua WiFi",
  "intercom.setup.s2.d4": "Introdu parola rețelei",
  "intercom.setup.s3.title": "Configurare Aplicație",
  "intercom.setup.s3.desc": "Personalizează setările și adaugă utilizatori suplimentari",
  "intercom.setup.s3.d1": "Creează cont în aplicație",
  "intercom.setup.s3.d2": "Setează preferințele de notificări",
  "intercom.setup.s3.d3": "Adaugă membri ai familiei",
  "intercom.setup.s3.d4": "Configurează coduri de acces",
  "intercom.setup.s4.title": "Testare & Finalizare",
  "intercom.setup.s4.desc": "Verifică toate funcțiile și finalizează configurarea",
  "intercom.setup.s4.d1": "Testează comunicarea audio-video",
  "intercom.setup.s4.d2": "Verifică notificările push",
  "intercom.setup.s4.d3": "Testează deschiderea ușii",
  "intercom.setup.s4.d4": "Configurează scenarii automate",
  "intercom.features.title": "Funcționalități Avansate",
  "intercom.features.f1.title": "Video HD & Night Vision",
  "intercom.features.f1.desc": "Cameră HD cu vedere nocturnă și unghi larg de 160°",
  "intercom.features.f1.d1": "Rezoluție 1080p",
  "intercom.features.f1.d2": "Night vision IR",
  "intercom.features.f1.d3": "Unghi larg de vizualizare",
  "intercom.features.f1.d4": "Senzor de mișcare",
  "intercom.features.f2.title": "Audio Bidirectional",
  "intercom.features.f2.desc": "Comunicare clară în ambele sensuri cu reducere de zgomot",
  "intercom.features.f2.d1": "Microfon HD",
  "intercom.features.f2.d2": "Reducere zgomot",
  "intercom.features.f2.d3": "Echo cancellation",
  "intercom.features.f2.d4": "Volum ajustabil",
  "intercom.features.f3.title": "Control Acces",
  "intercom.features.f3.desc": "Multiple metode de acces și management utilizatori",
  "intercom.features.f3.d1": "Coduri PIN",
  "intercom.features.f3.d2": "Carduri RFID",
  "intercom.features.f3.d3": "Amprentă digitală",
  "intercom.features.f3.d4": "Recunoaștere facială",
  "intercom.features.f4.title": "Smart Integration",
  "intercom.features.f4.desc": "Integrare cu ecosistemul smart home și automatizări",
  "intercom.features.f4.d1": "Control din aplicație",
  "intercom.features.f4.d2": "Integrare Alexa/Google",
  "intercom.features.f4.d3": "Automatizări IFTTT",
  "intercom.features.f4.d4": "API deschis",
  "intercom.usecases.title": "Scenarii de Utilizare",
  "intercom.usecases.family.title": "Pentru Familii",
  "intercom.usecases.family.s1": "Monitorizare copii când ajung acasă",
  "intercom.usecases.family.s2": "Acces pentru bone sau îngrijitori",
  "intercom.usecases.family.s3": "Comunicare cu vizitatori când nu ești acasă",
  "intercom.usecases.family.s4": "Înregistrare video pentru siguranță",
  "intercom.usecases.business.title": "Pentru Business",
  "intercom.usecases.business.s1": "Control acces angajați",
  "intercom.usecases.business.s2": "Programare vizite",
  "intercom.usecases.business.s3": "Monitorizare livrări",
  "intercom.usecases.business.s4": "Istoric complet al accesului",
  "intercom.usecases.vacation.title": "Pentru Vacanțe",
  "intercom.usecases.vacation.s1": "Acces pentru oaspeți Airbnb",
  "intercom.usecases.vacation.s2": "Monitorizare de la distanță",
  "intercom.usecases.vacation.s3": "Coduri temporare de acces",
  "intercom.usecases.vacation.s4": "Comunicare cu servicii de curățenie",
  "intercom.security.title": "Securitate și Confidențialitate",
  "intercom.security.e2e.title": "Criptare End-to-End",
  "intercom.security.e2e.desc": "Toate comunicațiile video și audio sunt criptate pentru maximă siguranță",
  "intercom.security.control.title": "Control Total asupra Datelor",
  "intercom.security.control.desc": "Tu decizi cât timp se păstrează înregistrările și cine are acces la ele",
  "intercom.security.protection.title": "Protecție Avansată",
  "intercom.security.protection.desc": "Sistem anti-tamper și alertare în timp real la activități suspecte",
  "intercom.products.title": "Produse Smart pentru Interfon",
};

export type TranslationKey = keyof typeof translationKeysEn;

type Translations = typeof translationKeysEn;
type AllTranslations = { en: Translations; ro: Record<TranslationKey, string> };

const translations: AllTranslations = {
  en: translationKeysEn,
  ro: translationKeysRo,
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language") as Language | null;
      return saved === "en" || saved === "ro" ? saved : "ro";
    }
    return "ro";
  });

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("language", lang);
    }
  };

  const t = (key: TranslationKey): string => {
    return translations[language]?.[key] ?? translations.en[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
